/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateDuaInput {
  'title' : string,
  'content' : string,
  'audio' : [] | [ExternalBlob],
}
export interface CreatePoetryInput {
  'title' : string,
  'content' : string,
  'image' : [] | [ExternalBlob],
}
export interface CreateSongInput {
  'title' : string,
  'audio' : ExternalBlob,
  'artist' : string,
}
export interface Dua {
  'id' : string,
  'title' : string,
  'likeCount' : bigint,
  'content' : string,
  'audio' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'category' : string,
}
export type ExternalBlob = Uint8Array;
export interface Poetry {
  'id' : string,
  'title' : string,
  'likeCount' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'category' : string,
  'image' : [] | [ExternalBlob],
}
export interface Song {
  'id' : string,
  'title' : string,
  'likeCount' : bigint,
  'audio' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'category' : string,
  'artist' : string,
}
export interface UserProfile { 'name' : string }
export interface UserRecord {
  'isBlocked' : boolean,
  'name' : string,
  'server' : string,
  'uniqueCode' : string,
  'deviceId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[string], undefined>,
  'createDua' : ActorMethod<[CreateDuaInput], string>,
  'createPoetry' : ActorMethod<[CreatePoetryInput], string>,
  'createSong' : ActorMethod<[CreateSongInput], string>,
  'deleteDua' : ActorMethod<[string], boolean>,
  'deletePoetry' : ActorMethod<[string], boolean>,
  'deleteSong' : ActorMethod<[string], boolean>,
  'getAllDua' : ActorMethod<[], Array<Dua>>,
  'getAllPoetry' : ActorMethod<[], Array<Poetry>>,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getAllUsers' : ActorMethod<[], Array<UserRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDuaById' : ActorMethod<[string], [] | [Dua]>,
  'getMaintenanceMode' : ActorMethod<[], boolean>,
  'getPoetryById' : ActorMethod<[string], [] | [Poetry]>,
  'getSongById' : ActorMethod<[string], [] | [Song]>,
  'getUserByDeviceId' : ActorMethod<[string], [] | [UserRecord]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementDuaLike' : ActorMethod<[string], bigint>,
  'incrementPoetryLike' : ActorMethod<[string], bigint>,
  'incrementSongLike' : ActorMethod<[string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMaintenanceMode' : ActorMethod<[boolean], undefined>,
  'unblockUser' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];