/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateDuaInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'audio' : IDL.Opt(ExternalBlob),
});
export const CreatePoetryInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const CreateSongInput = IDL.Record({
  'title' : IDL.Text,
  'audio' : ExternalBlob,
  'artist' : IDL.Text,
});
export const Likes = IDL.Record({
  'count' : IDL.Nat,
  'likedBy' : IDL.Vec(IDL.Text),
});
export const Dua = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'audio' : IDL.Opt(ExternalBlob),
  'likes' : Likes,
  'category' : IDL.Text,
});
export const Poetry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'likes' : Likes,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const Song = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'audio' : IDL.Opt(ExternalBlob),
  'category' : IDL.Text,
  'artist' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDua' : IDL.Func([CreateDuaInput], [IDL.Text], []),
  'createPoetry' : IDL.Func([CreatePoetryInput], [IDL.Text], []),
  'createSong' : IDL.Func([CreateSongInput], [IDL.Text], []),
  'deleteDua' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePoetry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteSong' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllDuas' : IDL.Func([], [IDL.Vec(Dua)], ['query']),
  'getAllPoetry' : IDL.Func([], [IDL.Vec(Poetry)], ['query']),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDuaById' : IDL.Func([IDL.Text], [IDL.Opt(Dua)], ['query']),
  'getDuaLikes' : IDL.Func([IDL.Text], [IDL.Opt(Likes)], ['query']),
  'getPoetryById' : IDL.Func([IDL.Text], [IDL.Opt(Poetry)], ['query']),
  'getPoetryLikes' : IDL.Func([IDL.Text], [IDL.Opt(Likes)], ['query']),
  'getSongById' : IDL.Func([IDL.Text], [IDL.Opt(Song)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeDua' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'likePoetry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateDuaInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'audio' : IDL.Opt(ExternalBlob),
  });
  const CreatePoetryInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const CreateSongInput = IDL.Record({
    'title' : IDL.Text,
    'audio' : ExternalBlob,
    'artist' : IDL.Text,
  });
  const Likes = IDL.Record({
    'count' : IDL.Nat,
    'likedBy' : IDL.Vec(IDL.Text),
  });
  const Dua = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'audio' : IDL.Opt(ExternalBlob),
    'likes' : Likes,
    'category' : IDL.Text,
  });
  const Poetry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'likes' : Likes,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Song = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'audio' : IDL.Opt(ExternalBlob),
    'category' : IDL.Text,
    'artist' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDua' : IDL.Func([CreateDuaInput], [IDL.Text], []),
    'createPoetry' : IDL.Func([CreatePoetryInput], [IDL.Text], []),
    'createSong' : IDL.Func([CreateSongInput], [IDL.Text], []),
    'deleteDua' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePoetry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteSong' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllDuas' : IDL.Func([], [IDL.Vec(Dua)], ['query']),
    'getAllPoetry' : IDL.Func([], [IDL.Vec(Poetry)], ['query']),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDuaById' : IDL.Func([IDL.Text], [IDL.Opt(Dua)], ['query']),
    'getDuaLikes' : IDL.Func([IDL.Text], [IDL.Opt(Likes)], ['query']),
    'getPoetryById' : IDL.Func([IDL.Text], [IDL.Opt(Poetry)], ['query']),
    'getPoetryLikes' : IDL.Func([IDL.Text], [IDL.Opt(Likes)], ['query']),
    'getSongById' : IDL.Func([IDL.Text], [IDL.Opt(Song)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeDua' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'likePoetry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };